- name: Install Git
  apt:
    name: git
    state: present

- name: Delete old website folder
  file:
    path: /var/www/html
    state: absent

- name: Create fresh website folder
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Clone Website from GitHub
  git:
    repo: "https://github.com/omwarkri/ansible-simple-app.git"
    dest: /var/www/html